-- MySQL Script generated by MySQL Workbench
-- Sun May 31 09:44:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema carritocompras
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `carritocompras` ;

-- -----------------------------------------------------
-- Schema carritocompras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carritocompras` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;
USE `carritocompras` ;

-- -----------------------------------------------------
-- Table `carritocompras`.`caromas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`caromas` (
  `ID` INT(11) NOT NULL,
  `aroma` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`chojasxrollo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`chojasxrollo` (
  `ID` INT(11) NOT NULL,
  `no_hojas` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`cliente` (
  `ID_cli` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cli` VARCHAR(45) NOT NULL,
  `appat_cli` VARCHAR(45) NOT NULL,
  `apmat_cli` VARCHAR(45) NOT NULL,
  `fecha_nacimiento_cli` DATE NULL DEFAULT NULL,
  `username_cli` VARCHAR(20) NOT NULL,
  `password_cli` VARCHAR(20) NOT NULL,
  `cel_cli` VARCHAR(12) NULL DEFAULT NULL,
  `tel_cli` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_cli`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`cmaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`cmaterial` (
  `ID` INT(11) NOT NULL,
  `Material` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`cordenservicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`cordenservicio` (
  `ID` INT(11) NOT NULL,
  `tipo_orden` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`cprivilegio_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`cprivilegio_empleado` (
  `ID` INT(11) NOT NULL,
  `tipo_privilegio` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`crollosincluidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`crollosincluidos` (
  `ID` INT(11) NOT NULL,
  `rollos` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`ctipo_hojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`ctipo_hojas` (
  `ID` INT(11) NOT NULL,
  `tipo_hojas` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`ctipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`ctipos` (
  `ID` INT(11) NOT NULL,
  `Tipos` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`ctipostendencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`ctipostendencia` (
  `ID_Ctipostendencias` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Ctipostendencias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`mcarritocompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`mcarritocompras` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `orden` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`mpapel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`mpapel` (
  `ID_mp` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_producto` VARCHAR(45) NULL DEFAULT NULL,
  `id_DPapel` INT(11) NOT NULL,
  PRIMARY KEY (`ID_mp`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`dcarritodecompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`dcarritodecompras` (
  `ID` INT(11) NOT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `Subtotal` DOUBLE NULL DEFAULT NULL,
  `fecha` DATETIME(4) NULL DEFAULT NULL,
  `MPapel_ID` INT(11) NOT NULL,
  `MCarritoCompras_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DCarritoDeCompras_MPapel1_idx` (`MPapel_ID` ASC) ,
  INDEX `fk_DCarritoDeCompras_MCarritoCompras1_idx` (`MCarritoCompras_ID` ASC) ,
  CONSTRAINT `fk_DCarritoDeCompras_MCarritoCompras1`
    FOREIGN KEY (`MCarritoCompras_ID`)
    REFERENCES `carritocompras`.`mcarritocompras` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DCarritoDeCompras_MPapel1`
    FOREIGN KEY (`MPapel_ID`)
    REFERENCES `carritocompras`.`mpapel` (`ID_mp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`dcompracliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`dcompracliente` (
  `ID` INT(11) NOT NULL,
  `Cliente_ID` INT(11) NOT NULL,
  `DCarritoDeCompras_ID` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CompraCliente_Cliente1_idx` (`Cliente_ID` ASC) ,
  INDEX `fk_CompraCliente_DCarritoDeCompras1_idx` (`DCarritoDeCompras_ID` ASC) ,
  CONSTRAINT `fk_CompraCliente_Cliente1`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `mydb`.`cliente` (`ID_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CompraCliente_DCarritoDeCompras1`
    FOREIGN KEY (`DCarritoDeCompras_ID`)
    REFERENCES `carritocompras`.`dcarritodecompras` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`empleado` (
  `ID_em` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_em` VARCHAR(45) NOT NULL,
  `Appat_em` VARCHAR(45) NOT NULL,
  `Apmat_em` VARCHAR(45) NOT NULL,
  `fecha_nacimiento_em` DATE NULL DEFAULT NULL,
  `cel_em` INT(11) NULL DEFAULT NULL,
  `tel_em` INT(11) NULL DEFAULT NULL,
  `username_em` VARCHAR(20) NOT NULL,
  `password_em` VARCHAR(20) NOT NULL,
  `CPrivilegio_Empleado_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID_em`),
  INDEX `fk_Empleado_CPrivilegio_Empleado1_idx` (`CPrivilegio_Empleado_ID` ASC) ,
  CONSTRAINT `fk_Empleado_CPrivilegio_Empleado1`
    FOREIGN KEY (`CPrivilegio_Empleado_ID`)
    REFERENCES `carritocompras`.`cprivilegio_empleado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`dordenservicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`dordenservicio` (
  `ID` INT(11) NOT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `Cliente_ID` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `Empleado_ID` INT(11) NOT NULL,
  `COrdenServicio_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DOrdenServicio_Cliente1_idx` (`Cliente_ID` ASC) ,
  INDEX `fk_DOrdenServicio_Empleado1_idx` (`Empleado_ID` ASC) ,
  INDEX `fk_DOrdenServicio_COrdenServicio1_idx` (`COrdenServicio_ID` ASC) ,
  CONSTRAINT `fk_DOrdenServicio_COrdenServicio1`
    FOREIGN KEY (`COrdenServicio_ID`)
    REFERENCES `carritocompras`.`cordenservicio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOrdenServicio_Cliente1`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `carritocompras`.`cliente` (`ID_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOrdenServicio_Empleado1`
    FOREIGN KEY (`Empleado_ID`)
    REFERENCES `carritocompras`.`empleado` (`ID_em`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`dpapel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`dpapel` (
  `ID_dp` INT(11) NOT NULL AUTO_INCREMENT,
  `Precio` DOUBLE NOT NULL,
  `Stock` INT(11) NOT NULL,
  `CMaterial_ID` INT(11) NOT NULL,
  `CTipos_ID` INT(11) NOT NULL,
  `Aromas_ID` INT(11) NOT NULL,
  `CRollosIncluidos_ID` INT(11) NOT NULL,
  `CTipo_Hojas_ID` INT(11) NOT NULL,
  `CHojasxRollo_ID` INT(11) NOT NULL,
  `img_ruta` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_dp`),
  INDEX `fk_Papel_CMaterial` (`CMaterial_ID` ASC) ,
  INDEX `fk_Papel_CTipos1` (`CTipos_ID` ASC) ,
  INDEX `fk_DPapel_Aromas1` (`Aromas_ID` ASC) ,
  INDEX `fk_DPapel_CRollosIncluidos1` (`CRollosIncluidos_ID` ASC) ,
  INDEX `fk_DPapel_CTipo_Hojas1` (`CTipo_Hojas_ID` ASC) ,
  INDEX `fk_DPapel_CHojasxRollo1` (`CHojasxRollo_ID` ASC) ,
  CONSTRAINT `fk_DPapel_Aromas1`
    FOREIGN KEY (`Aromas_ID`)
    REFERENCES `carritocompras`.`caromas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPapel_CHojasxRollo1`
    FOREIGN KEY (`CHojasxRollo_ID`)
    REFERENCES `carritocompras`.`chojasxrollo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPapel_CRollosIncluidos1`
    FOREIGN KEY (`CRollosIncluidos_ID`)
    REFERENCES `carritocompras`.`crollosincluidos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPapel_CTipo_Hojas1`
    FOREIGN KEY (`CTipo_Hojas_ID`)
    REFERENCES `carritocompras`.`ctipo_hojas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DPapel_MPapel1`
    FOREIGN KEY (`ID_dp`)
    REFERENCES `carritocompras`.`mpapel` (`ID_mp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Papel_CMaterial`
    FOREIGN KEY (`CMaterial_ID`)
    REFERENCES `carritocompras`.`cmaterial` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Papel_CTipos1`
    FOREIGN KEY (`CTipos_ID`)
    REFERENCES `carritocompras`.`ctipos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carritocompras`.`motrdenservicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritocompras`.`motrdenservicio` (
  `ID` INT(11) NOT NULL,
  `DOrdenServicio_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MOtrdenServicio_DOrdenServicio1_idx` (`DOrdenServicio_ID` ASC) ,
  CONSTRAINT `fk_MOtrdenServicio_DOrdenServicio1`
    FOREIGN KEY (`DOrdenServicio_ID`)
    REFERENCES `carritocompras`.`dordenservicio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `carritocompras` ;

-- -----------------------------------------------------
-- procedure establecerTendencia
-- -----------------------------------------------------

DELIMITER $$
USE `carritocompras`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `establecerTendencia`(cantidad int, marca varchar(45), tipo varchar(45))
select unidades, marca from tendencias
where marca = marca$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure traducirIdesCatalogosCarrito
-- -----------------------------------------------------

DELIMITER $$
USE `carritocompras`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `traducirIdesCatalogosCarrito`(id_material int, id_tipos int, id_aroma int, id_rollos int, id_tipo_hojas int, id_hojas_rollos int)
select carritocompras.CMaterial.material, carritocompras.CTipos.Tipos, carritocompras.CAromas.Aroma, carritocompras.CRollosIncluidos.rollos, carritocompras.CTipo_Hojas.tipo_hojas, carritocompras.CHojasxRollo.no_hojas 
    from carritocompras.CMaterial, carritocompras.CTipos, carritocompras.CAromas, carritocompras.CRollosIncluidos, carritocompras.CTipo_Hojas,carritocompras.CHojasxRollo
    where carritocompras.CMaterial.ID = id_material AND
		carritocompras.CTipos.ID = id_tipos AND
        carritocompras.CAromas.ID = id_aroma AND
        carritocompras.CRollosIncluidos.ID = id_rollos AND
        carritocompras.CTipo_Hojas.ID = id_tipo_hojas AND
        carritocompras.CHojasxRollo.ID = id_hojas_rollos$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure traducirValoresCatalogosCarrito
-- -----------------------------------------------------

DELIMITER $$
USE `carritocompras`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `traducirValoresCatalogosCarrito`(mat varchar(20), tipo varchar(20), ar varchar(20), n_rollos int , tip_hojas varchar(10), hojas_rollos int)
select carritocompras.CMaterial.ID, carritocompras.CTipos.ID, carritocompras.CAromas.ID, carritocompras.CRollosIncluidos.ID, carritocompras.CTipo_Hojas.ID, carritocompras.CHojasxRollo.ID 
    from carritocompras.CMaterial, carritocompras.CTipos, carritocompras.CAromas, carritocompras.CRollosIncluidos, carritocompras.CTipo_Hojas,carritocompras.CHojasxRollo
    where carritocompras.CMaterial.material = mat AND
		carritocompras.CTipos.Tipos = tipo AND
        carritocompras.CAromas.Aroma = ar AND
        carritocompras.CRollosIncluidos.rollos = n_rollos AND
        carritocompras.CTipo_Hojas.tipo_hojas = tip_hojas AND
        carritocompras.CHojasxRollo.no_hojas = hojas_rollos$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
